version: '3.6'

services:
  api:
    image: quay.io/kamuridesu/whisper-local-ai
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/readyz"]
      interval: 1m
      timeout: 20m
      retries: 20
    ports:
      - 8080:8080
    environment:
      - DEBUG=true
      - MODELS_PATH=/models
      - 'PRELOAD_MODELS=[{"url": "github:go-skynet/model-gallery/whisper-base.yaml", "name": "whisper-1"}]'
    volumes:
      - ./models:/models:cached
    command: ["/usr/bin/local-ai" ]
